// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrDJDdA81PyB72Do9YrlxukiYl0CroLlA',
    appId: '1:761736797362:web:b3c7343db2cb73ebb57dab',
    messagingSenderId: '761736797362',
    projectId: 'chat-cfbb8',
    authDomain: 'chat-cfbb8.firebaseapp.com',
    storageBucket: 'chat-cfbb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWqPPOHxkSmp_gsSGI__iWcseOiGsbKus',
    appId: '1:761736797362:android:e03aa56910f815aeb57dab',
    messagingSenderId: '761736797362',
    projectId: 'chat-cfbb8',
    storageBucket: 'chat-cfbb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUuP0pamPgA4MSLdWekyVNzl2BiRGG9yg',
    appId: '1:761736797362:ios:86510bdc5beb40f5b57dab',
    messagingSenderId: '761736797362',
    projectId: 'chat-cfbb8',
    storageBucket: 'chat-cfbb8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUuP0pamPgA4MSLdWekyVNzl2BiRGG9yg',
    appId: '1:761736797362:ios:86510bdc5beb40f5b57dab',
    messagingSenderId: '761736797362',
    projectId: 'chat-cfbb8',
    storageBucket: 'chat-cfbb8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrDJDdA81PyB72Do9YrlxukiYl0CroLlA',
    appId: '1:761736797362:web:c4bf5de7e26951b4b57dab',
    messagingSenderId: '761736797362',
    projectId: 'chat-cfbb8',
    authDomain: 'chat-cfbb8.firebaseapp.com',
    storageBucket: 'chat-cfbb8.appspot.com',
  );

}